---
version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
    test:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: './terraform/aws'
          soft-fail: true

