version: 2.1

orbs:
    bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
    build:
      executor: bridgecrew/default
      steps:
        - run:
          - checkout
          - when:
            condition:
              equal: ["${CIRCLE_BRANCH}", "master"]
            steps:
              - bridgecrew/scan:
              directory: ./terraform/aws
              soft-fail: true # do not fail the workflow in case vulnerabilities have found.
