version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    executor: bridgecrew/default
    filters:
      branches:
        ignore: master
    steps:
      - checkout
      - bridgecrew/scan:
          directory: ./terraform/aws
          soft-fail: true
