version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    executor: bridgecrew/default
    steps:
      - checkout
      - when:
          condition:
            not:
              equal:
                - master
                - ${CIRCLE_BRANCH}
          steps:
            - bridgecrew/scan:
                directory: ./terraform/aws
                soft-fail: true
