version: 2.1

orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5

workflows:
  build:
    jobs:
      - security:
          filters:
            branches:
              ignore: master

jobs:
  security:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: ./terraform/aws
          soft-fail: true # do not fail the workflow in case vulnerabilities have been found.
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
