version: 2.1

orbs:
  checkov: bridgecrew/checkov@1.0.5

jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          file: "./terraform/db-app.tf"
          output: "json"