version: 2.1
orbs:
    bridgecrew: bridgecrew/bridgecrew@1.0.3

jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            
  test-scan:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: './terraform/aws'